fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    nexus: "git://github.com/NERC-CEH/puppet-nexus.git"
  symlinks:
    selendroid: "#{source_dir}"